[project]
name = "mathmodeling"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.5",
    "notebook>=7.4.5",
    "pandas>=2.3.1",
    "pandas-stubs==2.3.0.250703",
    "scikit-learn>=1.7.1",
    "seaborn>=0.13.2",
]
